### 181 데이터 처리하기 1) - 연도별 출생아 수 계산하기

In [1]:
a = '123'
print(a[:-1])

12

In [4]:
def countBirths():
    ret = []
    for y in range(1880,2016):
        count = 0
        filename = 'names/yob%s.txt' %y
        with open(filename, 'r') as f:
            data = f.readlines()
            for d in data:
                if d[-1] == '\n':
                    d = d[:-1]
                birth = d.split(',')[2]
                count += int(birth)
        ret.append((y,count))
    return ret

result = countBirths()
with open('birth_by_year.csv','w') as f:
    for year, birth in result:
        data = '%s,%s\n'%(year, birth)
        print(data)
        f.write(data)

1880,201483

1881,192696

1882,221533

1883,216945

1884,243463

1885,240854

1886,255317

1887,247396

1888,299475

1889,288947

1890,301401

1891,286673

1892,334375

1893,325222

1894,338691

1895,351023

1896,357485

1897,346958

1898,381459

1899,339234

1900,450296

1901,345817

1902,386735

1903,381205

1904,403489

1905,423937

1906,428462

1907,465395

1908,488652

1909,511230

1910,590717

1911,644279

1912,988064

1913,1137108

1914,1416331

1915,1832472

1916,1934435

1917,2006787

1918,2171171

1919,2110264

1920,2262705

1921,2334488

1922,2289200

1923,2302512

1924,2381673

1925,2333334

1926,2295922

1927,2319230

1928,2260773

1929,2191954

1930,2223111

1931,2103958

1932,2110985

1933,1999042

1934,2076448

1935,2089571

1936,2077311

1937,2130323

1938,2212260

1939,2203241

1940,2302361

1941,2436023

1942,2731426

1943,2822095

1944,2689804

1945,2652673

1946,3195038

1947,3602002

1948,3452269

1949,3484543

1950,3504130

1951,3684164

1952,3798049

1953,3851855

1954,3980407

1955,4012933

1956,4121130

1957,4200097

1958,4131802

1959,4156576

1960,4154809

1961,4140160

1962,4035499

1963,3958969

1964,3887976

1965,3626317

1966,3475867

1967,3395323

1968,3379149

1969,3476552

1970,3607798

1971,3432829

1972,3143875

1973,3017577

1974,3040567

1975,3020069

1976,3035135

1977,3176974

1978,3174315

1979,3327391

1980,3444418

1981,3458968

1982,3507375

1983,3462465

1984,3487484

1985,3567742

1986,3555473

1987,3604086

1988,3693102

1989,3843384

1990,3950720

1991,3894143

1992,3840017

1993,3769139

1994,3716629

1995,3661216

1996,3646119

1997,3624565

1998,3676838

1999,3692153

2000,3777666

2001,3741011

2002,3735651

2003,3799547

2004,3817903

2005,3841440

2006,3952231

2007,3993206

2008,3925486

2009,3814539

2010,3689517

2011,3650434

2012,3648441

2013,3634744

2014,3692930

2015,3683749

### 182 데이터 처리하기 2) - 연도별 성별 출생아 수 계산하기

In [7]:
def countBirthBysex():
    ret = []
    
    for y in range(1880,2016):
        count_f = 0
        count_m = 0
        
        filename = 'names/yob%s.txt' %y
        with open(filename,'r') as f:
            data = f.readlines()
            for d in data:
                if d[-1] == '\n':
                    d = d[:-1]
                sex = d.split(',')[1]
                
                if sex == 'F':
                    count_f += int(d.split(',')[2])
                else:
                    count_m += int(d.split(',')[2])
                    
            ret.append((y, count_f, count_m))
    return ret

result = countBirthBysex()
with open('birth_by_sex.csv','w') as f:
    for y,count_f,count_m in result:
        data = '%s,%s,%s\n' %(y,count_f,count_m)
        print(data)
        f.write(data)

1880,90992,110491

1881,91953,100743

1882,107847,113686

1883,112318,104627

1884,129020,114443

1885,133055,107799

1886,144533,110784

1887,145981,101415

1888,178624,120851

1889,178366,110581

1890,190376,111025

1891,185482,101191

1892,212339,122036

1893,212905,112317

1894,222922,115769

1895,233627,117396

1896,237918,119567

1897,234201,112757

1898,258769,122690

1899,233023,106211

1900,299810,150486

1901,239347,106470

1902,264076,122659

1903,261971,119234

1904,275364,128125

1905,291622,132315

1906,295303,133159

1907,318565,146830

1908,334313,154339

1909,347231,163999

1910,396502,194215

1911,418309,225970

1912,558116,429948

1913,624543,512565

1914,761568,654763

1915,983874,848598

1916,1044335,890100

1917,1081289,925498

1918,1157651,1013520

1919,1130134,980130

1920,1198288,1064417

1921,1233035,1101453

1922,1200952,1088248

1923,1206338,1096174

1924,1248903,1132770

1925,1217384,1115950

1926,1185380,1110542

1927,1192379,1126851

1928,1153188,1107585

1929,1116495,1075459

1930,1125853,1097258

1931,1064591,1039367

1932,1067026,1043959

1933,1007784,991258

1934,1044087,1032361

1935,1048492,1041079

1936,1040266,1037045

1937,1063902,1066421

1938,1103328,1108932

1939,1096588,1106653

1940,1143386,1158975

1941,1207968,1228055

1942,1350590,1380836

1943,1395150,1426945

1944,1327156,1362648

1945,1307030,1345643

1946,1571223,1623815

1947,1772681,1829321

1948,1697813,1754456

1949,1710832,1773711

1950,1713259,1790871

1951,1800899,1883265

1952,1854375,1943674

1953,1880850,1971005

1954,1942008,2038399

1955,1954733,2058200

1956,2007486,2113644

1957,2044226,2155871

1958,2010983,2120819

1959,2023113,2133463

1960,2022104,2132705

1961,2017508,2122652

1962,1966616,2068883

1963,1927302,2031667

1964,1894737,1993239

1965,1765114,1861203

1966,1691964,1783903

1967,1650881,1744442

1968,1640232,1738917

1969,1687035,1789517

1970,1748270,1859528

1971,1663628,1769201

1972,1521226,1622649

1973,1458210,1559367

1974,1467455,1573112

1975,1457817,1562252

1976,1465180,1569955

1977,1533133,1643841

1978,1531822,1642493

1979,1605195,1722196

1980,1660152,1784266

1981,1667684,1791284

1982,1692952,1814423

1983,1670262,1792203

1984,1683235,1804249

1985,1720297,1847445

1986,1714905,1840568

1987,1738099,1865987

1988,1780123,1912979

1989,1843219,2000165

1990,1897940,2052780

1991,1874529,2019614

1992,1843446,1996571

1993,1808577,1960562

1994,1785246,1931383

1995,1758107,1903109

1996,1752455,1893664

1997,1740104,1884461

1998,1766237,1910601

1999,1772978,1919175

2000,1814922,1962744

2001,1799416,1941595

2002,1795556,1940095

2003,1825722,1973825

2004,1834632,1983271

2005,1845978,1995462

2006,1899166,2053065

2007,1920231,2072975

2008,1888177,2037309

2009,1834048,1980491

2010,1774186,1915331

2011,1755278,1895156

2012,1756347,1892094

2013,1749061,1885683

2014,1779496,1913434

2015,1776538,1907211

### 183 데이터 처리하기 3) - 연도별 인기있는 상위 10개 성별 출생아 이름 구하기

In [2]:
from os.path import exists

def getTop10BaybyName(year):
    nameF = {}
    nameM = {}
    
    filename = 'names/yob%s.txt' % year
    if not exists(filename):
        print('[%s]파일이 존재하지 않음' %filename)
        return None
    
    with open(filename, 'r') as f:
        data = f.readlines()
        for d in data:
            if d[-1]=='\n':
                d = d[:-1]
            name = d.split(',')[0]
            sex = d.split(',')[1]
            count = int(d.split(',')[2])
            
            if sex =='F':
                ret = nameF
            else:
                ret = nameM
            if name in ret:
                ret[name] += count
            else:
                ret[name] = count
            
    retF = sorted(nameF.items(), key=lambda x:x[1], reverse = True)
    retM = sorted(nameM.items(), key = lambda x:x[1], reverse = True)
    
    
    for i, name in enumerate(retF):
        if i>9:
            break
        print('Top %d 여자아기 이름 : %s'%(i+1,name))
        
    for i, name in enumerate(retM):
        if i>9:
            break
        print('Top %d 남자아기 이름 : %s'%(i+1,name))
        
        
y = input('인기순 상위 10개 이름을 알고 싶은 출생년도를 입력하세요')
getTop10BaybyName(y)

인기순 상위 10개 이름을 알고 싶은 출생년도를 입력하세요1898
Top 1 여자아기 이름 : ('Mary', 14406)
Top 2 여자아기 이름 : ('Anna', 5773)
Top 3 여자아기 이름 : ('Helen', 5230)
Top 4 여자아기 이름 : ('Margaret', 4696)
Top 5 여자아기 이름 : ('Ruth', 4249)
Top 6 여자아기 이름 : ('Florence', 3790)
Top 7 여자아기 이름 : ('Elizabeth', 3659)
Top 8 여자아기 이름 : ('Ethel', 3531)
Top 9 여자아기 이름 : ('Marie', 3435)
Top 10 여자아기 이름 : ('Lillian', 3061)
Top 1 남자아기 이름 : ('John', 8159)
Top 2 남자아기 이름 : ('William', 7400)
Top 3 남자아기 이름 : ('James', 5321)
Top 4 남자아기 이름 : ('George', 4853)
Top 5 남자아기 이름 : ('Charles', 3557)
Top 6 남자아기 이름 : ('Joseph', 3171)
Top 7 남자아기 이름 : ('Robert', 2932)
Top 8 남자아기 이름 : ('Frank', 2925)
Top 9 남자아기 이름 : ('Edward', 2337)
Top 10 남자아기 이름 : ('Thomas', 2161)